/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import Controle.Conexao;
import Controle.Usuario_BD;
import Modelo.Usuario;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.JOptionPane;   
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro
 */

public class Gerenciar_Pizzas extends javax.swing.JFrame {
  
    String nome,email,senha,telefone,cargo;
    
    public Gerenciar_Pizzas() {
        initComponents();
        
        inicializaCampos_tabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_Voltar = new javax.swing.JButton();
        txtBox_nome = new javax.swing.JTextField();
        txtBox_email = new javax.swing.JTextField();
        txtBox_senha = new javax.swing.JTextField();
        txtBox_telefone = new javax.swing.JTextField();
        cmbBox_cargo = new javax.swing.JComboBox<>();
        btn_cadastrarFuncionario = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Usuarios = new javax.swing.JTable();
        btn_alterarFuncionario = new javax.swing.JButton();
        btn_removerFuncionario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel1.setText("TECNO-PIZZA");

        btn_Voltar.setBackground(new java.awt.Color(0, 204, 51));
        btn_Voltar.setText("⬅️ Voltar");
        btn_Voltar.setBorderPainted(false);
        btn_Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Voltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtBox_nome.setText("Nome");

        txtBox_email.setText("Email");

        txtBox_senha.setText("Senha");

        txtBox_telefone.setText("Telefone");

        cmbBox_cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Usuário", "Administrador" }));

        btn_cadastrarFuncionario.setBackground(new java.awt.Color(0, 153, 0));
        btn_cadastrarFuncionario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn_cadastrarFuncionario.setText("CADASTRAR");
        btn_cadastrarFuncionario.setBorderPainted(false);
        btn_cadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarFuncionarioActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Adicionar novo funcionário ao sistema");

        tbl_Usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Email", "Telefone", "Cargo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_UsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Usuarios);

        btn_alterarFuncionario.setBackground(new java.awt.Color(0, 153, 0));
        btn_alterarFuncionario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn_alterarFuncionario.setText("ALTERAR");
        btn_alterarFuncionario.setBorderPainted(false);
        btn_alterarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_alterarFuncionarioActionPerformed(evt);
            }
        });

        btn_removerFuncionario.setBackground(new java.awt.Color(153, 0, 51));
        btn_removerFuncionario.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn_removerFuncionario.setForeground(new java.awt.Color(255, 255, 255));
        btn_removerFuncionario.setText("EXCLUIR");
        btn_removerFuncionario.setBorderPainted(false);
        btn_removerFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtBox_nome)
                            .addComponent(txtBox_email, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtBox_senha, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(txtBox_telefone, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(cmbBox_cargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(btn_cadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_alterarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_removerFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtBox_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBox_email, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBox_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBox_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cmbBox_cargo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_alterarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_removerFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(184, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Formulario
    private Usuario getDados_Funcionario() {
        Usuario getDadosFuncionario = new Usuario();
        getDadosFuncionario.setNome(this.txtBox_nome.getText());
        getDadosFuncionario.setEmail(this.txtBox_email.getText());
        getDadosFuncionario.setSenha(this.txtBox_senha.getText());
        getDadosFuncionario.setTelefone(this.txtBox_telefone.getText());
 
        getDadosFuncionario.setCargo((String) this.cmbBox_cargo.getSelectedItem());
        return getDadosFuncionario;
    }
    
    //Tabela
    private ArrayList <Usuario> getDataTabelaFuncionario() {
        int i;
        DefaultTableModel model=(DefaultTableModel)tbl_Usuarios.getModel();
        model.setNumRows(0);

        ArrayList<Usuario> listaFuncionarios = new ArrayList<Usuario>();
        listaFuncionarios= new Usuario_BD().getListaFuncionarios();
        //adiciona alunos as tabelas
        for (i=0;i<=listaFuncionarios.size()-1;i++){
            model.addRow(new Object[]{listaFuncionarios.get(i).getNome(),listaFuncionarios.get(i).getEmail(),listaFuncionarios.get(i).getTelefone(),listaFuncionarios.get(i).getCargo()});
        }
        return listaFuncionarios;
    }
    
    //Zera os campos do formulario
    private void limpaCampos(){
        this.txtBox_nome.setText("Nome");
        this.txtBox_email.setText("Email");
        this.txtBox_telefone.setText("Telefone");
        this.txtBox_senha.setText("Senha");
    }
    
    private void inicializaCampos_tabela() {
        getDataTabelaFuncionario();
        limpaCampos();
    }
    
    
    
    private void btn_cadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarFuncionarioActionPerformed
        Usuario_BD cadastrar_funcionario = new Usuario_BD();
        
        if (cadastrar_funcionario.cadastrarFuncionario(getDados_Funcionario()))
        {
            JOptionPane.showMessageDialog(this, "Incluido com sucesso!", "Manutenção", 1);
            
        } else {
            JOptionPane.showMessageDialog(this, "Inclusão não realizada! Verifique se todos os campos estão preenchidos ou se o usuário já existe no sistema!", "Manutenção", 0);
        }
        inicializaCampos_tabela();
    }//GEN-LAST:event_btn_cadastrarFuncionarioActionPerformed

    private void tbl_UsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_UsuariosMouseClicked
        // função do clique do mouse selecionar linha da tabela:
         if (evt.getClickCount()==2)
         {
                         
            Connection con = null;
            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/tecno_pizza", "root", "");
                java.sql.Statement stm = con.createStatement();
                String SQL = "Select * from usuarios where email = '"+tbl_Usuarios.getValueAt(tbl_Usuarios.getSelectedRow(), 1).toString()+"';";
                
                ResultSet rs = stm.executeQuery(SQL);
                
                
                while (rs.next()){
                nome = rs.getString("nome");
                senha = rs.getString("senha");
                email = rs.getString("email");
                telefone = rs.getString("telefone");
                cargo = rs.getString("cargo");
                }
                     
            }catch(SQLException e){
                e.printStackTrace(); //vejamos que erro foi gerado e quem o gerou
                JOptionPane.showMessageDialog(null,"Erro na conexÃ£o, com o banco de dados!","Oi. Simples assim!",JOptionPane.WARNING_MESSAGE);
            }catch (ClassNotFoundException e) 
            {
                e.printStackTrace();
            }
            finally
            {
                try{
                    con.close();
                }catch(SQLException onConClose){
                    //System.out.println("Houve erro no fechamento da conexÃ£o");
                    JOptionPane.showMessageDialog(null,"Erro na conexÃ£o, com o banco de dados!","Oi. Simples assim!",JOptionPane.WARNING_MESSAGE);
                    onConClose.printStackTrace();
                }
            } 
        
            txtBox_senha.setText(senha);
            
            System.out.println(cargo);
            
            if (cargo == "Administrador") {
                cmbBox_cargo.setSelectedItem("Administrador");
            }
            else {
                cmbBox_cargo.setSelectedItem("Usuario");
            }
            
            
           
            txtBox_nome.setText(tbl_Usuarios.getValueAt(tbl_Usuarios.getSelectedRow(), 0).toString());
            txtBox_email.setText(tbl_Usuarios.getValueAt(tbl_Usuarios.getSelectedRow(), 1).toString());
            txtBox_telefone.setText(tbl_Usuarios.getValueAt(tbl_Usuarios.getSelectedRow(), 2).toString());
          
         }
    }//GEN-LAST:event_tbl_UsuariosMouseClicked

    private void btn_alterarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_alterarFuncionarioActionPerformed
        Usuario_BD Funcionario = new Usuario_BD();
        if (Funcionario.atualizarFuncionario(getDados_Funcionario())) {
            JOptionPane.showMessageDialog(this,"Atualizado com sucesso!", "Manutenção",1);
        } else {
            JOptionPane.showMessageDialog(this, "Atualização não realizada!", "Manutenção", 0);
        }
        this.inicializaCampos_tabela();
    }//GEN-LAST:event_btn_alterarFuncionarioActionPerformed

    private void btn_removerFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerFuncionarioActionPerformed
        Usuario_BD Funcionario = new Usuario_BD();
        if (JOptionPane.showConfirmDialog(rootPane, "Confirma exclusão?", "Confirmação de exlusão", 1, 1)==0){
            if (Funcionario.excluirFuncionario(this.getDados_Funcionario())){
                JOptionPane.showMessageDialog(this,"Excluido com sucesso!", "Manutenção",1);
            }else {
                JOptionPane.showMessageDialog(this, "Exclusão não realizada!", "Manutenção", 0);
            }
            this.inicializaCampos_tabela(); 
        } else {
            JOptionPane.showMessageDialog(this, "Exclusão cancelada pelo usuário!", "Manutenção", 0);
        }
    }//GEN-LAST:event_btn_removerFuncionarioActionPerformed

    private void btn_VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VoltarActionPerformed
        Principal_Administrador Tela_Adm = new Principal_Administrador();

        Tela_Adm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gerenciar_Pizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gerenciar_Pizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gerenciar_Pizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gerenciar_Pizzas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gerenciar_Pizzas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Voltar;
    private javax.swing.JButton btn_alterarFuncionario;
    private javax.swing.JButton btn_cadastrarFuncionario;
    private javax.swing.JButton btn_removerFuncionario;
    private javax.swing.JComboBox<String> cmbBox_cargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Usuarios;
    private javax.swing.JTextField txtBox_email;
    private javax.swing.JTextField txtBox_nome;
    private javax.swing.JTextField txtBox_senha;
    private javax.swing.JTextField txtBox_telefone;
    // End of variables declaration//GEN-END:variables
}
